version: '3.3'
services:
  jenkins:
      build: .
      restart: unless-stopped
      privileged: true
      user: root
      ports:
        - 8080:8080
      container_name: jenkins
      volumes:
        - ./jenkins:/var/jenkins_home
        - ./casc:/var/casc/
        - ./secrets:/var/lib/secrets
      environment:
        JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin # bad idea, this is to ease up the setup
        CASC_JENKINS_CONFIG: /var/casc/
  grafana:
    image: grafana/grafana:9.1.2
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana/
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb/
    restart: always

  builder:
    build:
      context: .
      dockerfile: ./go-docker
    restart: unless-stopped
    ports:
      - "9000:22"
